package com.example.android.klasyfikatorptakow_wdssn.cnn

object Labels {
    var LABELS = arrayOf(
        "Abbotts Babbler",
        "Abbotts Booby",
        "Abyssinian Ground Hornbill",
        "African Crowned Crane",
        "African Emerald Cuckoo",
        "African Firefinch",
        "African Oyster Catcher",
        "African Pied Hornbill",
        "African Pygmy Goose",
        "Albatross",
        "Alberts Towhee",
        "Alexandrine Parakeet",
        "Alpine Chough",
        "Altamira Yellowthroat",
        "American Avocet",
        "American Bittern",
        "American Coot",
        "American Dipper",
        "American Flamingo",
        "American Goldfinch",
        "American Kestrel",
        "American Pipit",
        "American Redstart",
        "American Robin",
        "American Wigeon",
        "Amethyst Woodstar",
        "Andean Goose",
        "Andean Lapwing",
        "Andean Siskin",
        "Anhinga",
        "Anianiau",
        "Annas Hummingbird",
        "Antbird",
        "Antillean Euphonia",
        "Apapane",
        "Apostlebird",
        "Araripe Manakin",
        "Ashy Storm Petrel",
        "Ashy Thrushbird",
        "Asian Crested Ibis",
        "Asian Dollard Bird",
        "Asian Green Bee Eater",
        "Asian Openbill Stork",
        "Auckland Shaq",
        "Austral Canastero",
        "Australasian Figbird",
        "Avadavat",
        "Azaras Spinetail",
        "Azure Breasted Pitta",
        "Azure Jay",
        "Azure Tanager",
        "Azure Tit",
        "Baikal Teal",
        "Bald Eagle",
        "Bald Ibis",
        "Bali Starling",
        "Baltimore Oriole",
        "Bananaquit",
        "Band Tailed Guan",
        "Banded Broadbill",
        "Banded Pita",
        "Banded Stilt",
        "Bar-Tailed Godwit",
        "Barn Owl",
        "Barn Swallow",
        "Barred Puffbird",
        "Barrows Goldeneye",
        "Bay-Breasted Warbler",
        "Bearded Barbet",
        "Bearded Bellbird",
        "Bearded Reedling",
        "Belted Kingfisher",
        "Bird Of Paradise",
        "Black And Yellow Broadbill",
        "Black Baza",
        "Black Breasted Puffbird",
        "Black Cockato",
        "Black Faced Spoonbill",
        "Black Francolin",
        "Black Headed Caique",
        "Black Necked Stilt",
        "Black Skimmer",
        "Black Swan",
        "Black Tail Crake",
        "Black Throated Bushtit",
        "Black Throated Huet",
        "Black Throated Warbler",
        "Black Vented Shearwater",
        "Black Vulture",
        "Black-Capped Chickadee",
        "Black-Necked Grebe",
        "Black-Throated Sparrow",
        "Blackburniam Warbler",
        "Blonde Crested Woodpecker",
        "Blood Pheasant",
        "Blue Coau",
        "Blue Dacnis",
        "Blue Gray Gnatcatcher",
        "Blue Grosbeak",
        "Blue Grouse",
        "Blue Heron",
        "Blue Malkoha",
        "Blue Throated Piping Guan",
        "Blue Throated Toucanet",
        "Bobolink",
        "Bornean Bristlehead",
        "Bornean Leafbird",
        "Bornean Pheasant",
        "Brandt Cormarant",
        "Brewers Blackbird",
        "Brown Crepper",
        "Brown Headed Cowbird",
        "Brown Noody",
        "Brown Thrasher",
        "Bufflehead",
        "Bulwers Pheasant",
        "Burchells Courser",
        "Bush Turkey",
        "Caatinga Cacholote",
        "Cabots Tragopan",
        "Cactus Wren",
        "California Condor",
        "California Gull",
        "California Quail",
        "Campo Flicker",
        "Canary",
        "Canvasback",
        "Cape Glossy Starling",
        "Cape Longclaw",
        "Cape May Warbler",
        "Cape Rock Thrush",
        "Capped Heron",
        "Capuchinbird",
        "Carmine Bee-Eater",
        "Caspian Tern",
        "Cassowary",
        "Cedar Waxwing",
        "Cerulean Warbler",
        "Chara De Collar",
        "Chattering Lory",
        "Chestnet Bellied Euphonia",
        "Chestnut Winged Cuckoo",
        "Chinese Bamboo Partridge",
        "Chinese Pond Heron",
        "Chipping Sparrow",
        "Chucao Tapaculo",
        "Chukar Partridge",
        "Cinnamon Attila",
        "Cinnamon Flycatcher",
        "Cinnamon Teal",
        "Clarks Grebe",
        "Clarks Nutcracker",
        "Cock Of The Rock",
        "Cockatoo",
        "Collared Aracari",
        "Collared Crescentchest",
        "Common Firecrest",
        "Common Grackle",
        "Common House Martin",
        "Common Iora",
        "Common Loon",
        "Common Poorwill",
        "Common Starling",
        "Coppersmith Barbet",
        "Coppery Tailed Coucal",
        "Crab Plover",
        "Crane Hawk",
        "Cream Colored Woodpecker",
        "Crested Auklet",
        "Crested Caracara",
        "Crested Coua",
        "Crested Fireback",
        "Crested Kingfisher",
        "Crested Nuthatch",
        "Crested Oropendola",
        "Crested Serpent Eagle",
        "Crested Shriketit",
        "Crested Wood Partridge",
        "Crimson Chat",
        "Crimson Sunbird",
        "Crow",
        "Cuban Tody",
        "Cuban Trogon",
        "Curl Crested Aracuri",
        "D-Arnauds Barbet",
        "Dalmatian Pelican",
        "Darjeeling Woodpecker",
        "Dark Eyed Junco",
        "Daurian Redstart",
        "Demoiselle Crane",
        "Double Barred Finch",
        "Double Brested Cormarant",
        "Double Eyed Fig Parrot",
        "Downy Woodpecker",
        "Dunlin",
        "Dusky Lory",
        "Dusky Robin",
        "Eared Pita",
        "Eastern Bluebird",
        "Eastern Bluebonnet",
        "Eastern Golden Weaver",
        "Eastern Meadowlark",
        "Eastern Rosella",
        "Eastern Towee",
        "Eastern Wip Poor Will",
        "Eastern Yellow Robin",
        "Ecuadorian Hillstar",
        "Egyptian Goose",
        "Elegant Trogon",
        "Elliots Pheasant",
        "Emerald Tanager",
        "Emperor Penguin",
        "Emu",
        "Enggano Myna",
        "Eurasian Bullfinch",
        "Eurasian Golden Oriole",
        "Eurasian Magpie",
        "European Goldfinch",
        "European Turtle Dove",
        "Evening Grosbeak",
        "Fairy Bluebird",
        "Fairy Penguin",
        "Fairy Tern",
        "Fan Tailed Widow",
        "Fasciated Wren",
        "Fiery Minivet",
        "Fiordland Penguin",
        "Fire Tailled Myzornis",
        "Flame Bowerbird",
        "Flame Tanager",
        "Forest Wagtail",
        "Frigate",
        "Frill Back Pigeon",
        "Gambels Quail",
        "Gang Gang Cockatoo",
        "Gila Woodpecker",
        "Gilded Flicker",
        "Glossy Ibis",
        "Go Away Bird",
        "Gold Wing Warbler",
        "Golden Bower Bird",
        "Golden Cheeked Warbler",
        "Golden Chlorophonia",
        "Golden Eagle",
        "Golden Parakeet",
        "Golden Pheasant",
        "Golden Pipit",
        "Gouldian Finch",
        "Grandala",
        "Gray Catbird",
        "Gray Kingbird",
        "Gray Partridge",
        "Great Argus",
        "Great Gray Owl",
        "Great Jacamar",
        "Great Kiskadee",
        "Great Potoo",
        "Great Tinamou",
        "Great Xenops",
        "Greater Pewee",
        "Greater Prairie Chicken",
        "Greator Sage Grouse",
        "Green Broadbill",
        "Green Jay",
        "Green Magpie",
        "Green Winged Dove",
        "Grey Cuckooshrike",
        "Grey Headed Chachalaca",
        "Grey Headed Fish Eagle",
        "Grey Plover",
        "Groved Billed Ani",
        "Guinea Turaco",
        "Guineafowl",
        "Gurneys Pitta",
        "Gyrfalcon",
        "Hamerkop",
        "Harlequin Duck",
        "Harlequin Quail",
        "Harpy Eagle",
        "Hawaiian Goose",
        "Hawfinch",
        "Helmet Vanga",
        "Hepatic Tanager",
        "Himalayan Bluetail",
        "Himalayan Monal",
        "Hoatzin",
        "Hooded Merganser",
        "Hoopoes",
        "Horned Guan",
        "Horned Lark",
        "Horned Sungem",
        "House Finch",
        "House Sparrow",
        "Hyacinth Macaw",
        "Iberian Magpie",
        "Ibisbill",
        "Imperial Shaq",
        "Inca Tern",
        "Indian Bustard",
        "Indian Pitta",
        "Indian Roller",
        "Indian Vulture",
        "Indigo Bunting",
        "Indigo Flycatcher",
        "Inland Dotterel",
        "Ivory Billed Aracari",
        "Ivory Gull",
        "Iwi",
        "Jabiru",
        "Jack Snipe",
        "Jacobin Pigeon",
        "Jandaya Parakeet",
        "Japanese Robin",
        "Java Sparrow",
        "Jocotoco Antpitta",
        "Kagu",
        "Kakapo",
        "Killdear",
        "King Eider",
        "King Vulture",
        "Kiwi",
        "Knob Billed Duck",
        "Kookaburra",
        "Lark Bunting",
        "Laughing Gull",
        "Lazuli Bunting",
        "Lesser Adjutant",
        "Lilac Roller",
        "Limpkin",
        "Little Auk",
        "Loggerhead Shrike",
        "Long-Eared Owl",
        "Looney Birds",
        "Lucifer Hummingbird",
        "Magpie Goose",
        "Malabar Hornbill",
        "Malachite Kingfisher",
        "Malagasy White Eye",
        "Maleo",
        "Mallard Duck",
        "Mandrin Duck",
        "Mangrove Cuckoo",
        "Marabou Stork",
        "Masked Bobwhite",
        "Masked Booby",
        "Masked Lapwing",
        "Mckays Bunting",
        "Merlin",
        "Mikado Pheasant",
        "Military Macaw",
        "Mourning Dove",
        "Myna",
        "Nicobar Pigeon",
        "Noisy Friarbird",
        "Northern Beardless Tyrannulet",
        "Northern Cardinal",
        "Northern Flicker",
        "Northern Fulmar",
        "Northern Gannet",
        "Northern Goshawk",
        "Northern Jacana",
        "Northern Mockingbird",
        "Northern Parula",
        "Northern Red Bishop",
        "Northern Shoveler",
        "Ocellated Turkey",
        "Oilbird",
        "Okinawa Rail",
        "Orange Breasted Trogon",
        "Orange Brested Bunting",
        "Oriental Bay Owl",
        "Ornate Hawk Eagle",
        "Osprey",
        "Ostrich",
        "Ovenbird",
        "Oyster Catcher",
        "Painted Bunting",
        "Palila",
        "Palm Nut Vulture",
        "Paradise Tanager",
        "Parakeet Auklet",
        "Parus Major",
        "Patagonian Sierra Finch",
        "Peacock",
        "Peregrine Falcon",
        "Phainopepla",
        "Philippine Eagle",
        "Pink Robin",
        "Plush Crested Jay",
        "Pomarine Jaeger",
        "Puffin",
        "Puna Teal",
        "Purple Finch",
        "Purple Gallinule",
        "Purple Martin",
        "Purple Swamphen",
        "Pygmy Kingfisher",
        "Pyrrhuloxia",
        "Quetzal",
        "Rainbow Lorikeet",
        "Razorbill",
        "Red Bearded Bee Eater",
        "Red Bellied Pitta",
        "Red Billed Tropicbird",
        "Red Browed Finch",
        "Red Crossbill",
        "Red Faced Cormorant",
        "Red Faced Warbler",
        "Red Fody",
        "Red Headed Duck",
        "Red Headed Woodpecker",
        "Red Knot",
        "Red Legged Honeycreeper",
        "Red Naped Trogon",
        "Red Shouldered Hawk",
        "Red Tailed Hawk",
        "Red Tailed Thrush",
        "Red Winged Blackbird",
        "Red Wiskered Bulbul",
        "Regent Bowerbird",
        "Ring-Necked Pheasant",
        "Roadrunner",
        "Rock Dove",
        "Rose Breasted Cockatoo",
        "Rose Breasted Grosbeak",
        "Roseate Spoonbill",
        "Rosy Faced Lovebird",
        "Rough Leg Buzzard",
        "Royal Flycatcher",
        "Ruby Crowned Kinglet",
        "Ruby Throated Hummingbird",
        "Ruddy Shelduck",
        "Rudy Kingfisher",
        "Rufous Kingfisher",
        "Rufous Trepe",
        "Rufuos Motmot",
        "Samatran Thrush",
        "Sand Martin",
        "Sandhill Crane",
        "Satyr Tragopan",
        "Says Phoebe",
        "Scarlet Crowned Fruit Dove",
        "Scarlet Faced Liocichla",
        "Scarlet Ibis",
        "Scarlet Macaw",
        "Scarlet Tanager",
        "Shoebill",
        "Short Billed Dowitcher",
        "Smiths Longspur",
        "Snow Goose",
        "Snow Partridge",
        "Snowy Egret",
        "Snowy Owl",
        "Snowy Plover",
        "Snowy Sheathbill",
        "Sora",
        "Spangled Cotinga",
        "Splendid Wren",
        "Spoon Biled Sandpiper",
        "Spotted Catbird",
        "Spotted Whistling Duck",
        "Squacco Heron",
        "Sri Lanka Blue Magpie",
        "Steamer Duck",
        "Stork Billed Kingfisher",
        "Striated Caracara",
        "Striped Owl",
        "Stripped Manakin",
        "Stripped Swallow",
        "Sunbittern",
        "Superb Starling",
        "Surf Scoter",
        "Swinhoes Pheasant",
        "Tailorbird",
        "Taiwan Magpie",
        "Takahe",
        "Tasmanian Hen",
        "Tawny Frogmouth",
        "Teal Duck",
        "Tit Mouse",
        "Touchan",
        "Townsends Warbler",
        "Tree Swallow",
        "Tricolored Blackbird",
        "Tropical Kingbird",
        "Trumpter Swan",
        "Turkey Vulture",
        "Turquoise Motmot",
        "Umbrella Bird",
        "Varied Thrush",
        "Veery",
        "Venezuelian Troupial",
        "Verdin",
        "Vermilion Flycather",
        "Victoria Crowned Pigeon",
        "Violet Backed Starling",
        "Violet Cuckoo",
        "Violet Green Swallow",
        "Violet Turaco",
        "Visayan Hornbill",
        "Vulturine Guineafowl",
        "Wall Creaper",
        "Wattled Curassow",
        "Wattled Lapwing",
        "Whimbrel",
        "White Breasted Waterhen",
        "White Browed Crake",
        "White Cheeked Turaco",
        "White Crested Hornbill",
        "White Eared Hummingbird",
        "White Necked Raven",
        "White Tailed Tropic",
        "White Throated Bee Eater",
        "Wild Turkey",
        "Willow Ptarmigan",
        "Wilsons Bird Of Paradise",
        "Wood Duck",
        "Wood Thrush",
        "Woodland Kingfisher",
        "Wrentit",
        "Yellow Bellied Flowerpecker",
        "Yellow Breasted Chat",
        "Yellow Cacique",
        "Yellow Headed Blackbird",
        "Zebra Dove"
    )
}